export const brandAssetManifest = {
  servicesGlow: ["/assets/live/J0CdaWzjawhE575G8LIv7rzAI.png", "/assets/live/brand-cyan/J0CdaWzjawhE575G8LIv7rzAI.png"],
  aboutLowerGlow: ["/assets/live/0pGuw8Zol1JkB8FhgdSyeOVr3M.png", "/assets/live/brand-cyan/0pGuw8Zol1JkB8FhgdSyeOVr3M.png"],
  foundingGlow: ["/assets/live/0X1CXp4xj8kowNCpRbYuUIVkaDQ.png", "/assets/live/brand-cyan/0X1CXp4xj8kowNCpRbYuUIVkaDQ.png"],
  ctaShade: ["/assets/live/f3uNp40z3hBKhBP8PvixWX6Ec.png", "/assets/live/brand-cyan/f3uNp40z3hBKhBP8PvixWX6Ec.png"],
  footerBackdrop: ["/assets/live/qfxmllsEQ8LT5FmJKm1sadVYsGg.png", "/assets/live/brand-cyan/qfxmllsEQ8LT5FmJKm1sadVYsGg.png"],
  comparisonSurface: ["/assets/live/Np6uOOX6ljuP6yy8IOfLZmdbXs.png", "/assets/live/brand-cyan/Np6uOOX6ljuP6yy8IOfLZmdbXs.png"],
  benefitsSurface: ["/assets/live/TPrC3O1we4x9Rds77byLoK7Ew.png", "/assets/live/brand-cyan/TPrC3O1we4x9Rds77byLoK7Ew.png"],
  featuredFrame: ["/assets/live/Ea995q8deCj9b3t43hhutnE8.png", "/assets/live/brand-cyan/Ea995q8deCj9b3t43hhutnE8.png"],
  contactAbstract: ["/assets/live/y48cq5SH9O3kuRoMxQPnzmqYg0.png", "/assets/live/brand-cyan/y48cq5SH9O3kuRoMxQPnzmqYg0.png"],
  ctaTexture: ["/assets/live/vPufXlAxj0qjF98pQCjoHGRq40.png", "/assets/live/brand-cyan/vPufXlAxj0qjF98pQCjoHGRq40.png"],
  routeBackdrop: ["/assets/live/hxv1k6QKnlVRWyZvet7V0Jn7iW0.png", "/assets/live/brand-cyan/hxv1k6QKnlVRWyZvet7V0Jn7iW0.png"],
  pricingSurface: ["/assets/live/vhYgDTNFd4rsboSMqUHqHGCWWQ.png", "/assets/live/brand-cyan/vhYgDTNFd4rsboSMqUHqHGCWWQ.png"],
  pricingBackdrop: ["/assets/live/ArOKS9oueStdoViN3FDHYzMN7JI.png", "/assets/live/brand-cyan/ArOKS9oueStdoViN3FDHYzMN7JI.png"],
  routeTexture: ["/assets/live/21Nxe9BjOK1MSyJrrYQgCDts.png", "/assets/live/brand-cyan/21Nxe9BjOK1MSyJrrYQgCDts.png"],
  sideDecoration: ["/assets/live/p66Ex21bxknbF6DJpl6fBENUyU.png", "/assets/live/brand-cyan/p66Ex21bxknbF6DJpl6fBENUyU.png"],
  ctaRim: ["/assets/live/3UCVA7YJLIIkMmFFtKOUVphg4.png", "/assets/live/brand-cyan/3UCVA7YJLIIkMmFFtKOUVphg4.png"],
  processCard: ["/assets/live/36VweI76iVkTEBB3r99TXNijRbg.png", "/assets/live/brand-cyan/36VweI76iVkTEBB3r99TXNijRbg.png"],
  pixelArrow: ["/assets/live/BQFGBP7rOiJsOjI0KKyLLQcyBLk.png", "/assets/live/brand-cyan/BQFGBP7rOiJsOjI0KKyLLQcyBLk.png"],
  teamAbstract: ["/assets/live/msMyC8COjFVKGxc0WC6uCnA5HvM.png", "/assets/live/brand-cyan/msMyC8COjFVKGxc0WC6uCnA5HvM.png"],
  teamSurface: ["/assets/live/4Lsc1onyNrhirkTEeDjiaifcy8k.png", "/assets/live/brand-cyan/4Lsc1onyNrhirkTEeDjiaifcy8k.png"],
  contactCornerLeft: ["/assets/live/al8BessOXQvdLkBex6RBcxQtJ9M.png", "/assets/live/brand-cyan/al8BessOXQvdLkBex6RBcxQtJ9M.png"],
  contactCornerRight: ["/assets/live/z6xuPZZvZXxALPYa8LR4mL7XLIA.png", "/assets/live/brand-cyan/z6xuPZZvZXxALPYa8LR4mL7XLIA.png"],
} as const;

